# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: chefchapters
  username: postgres
  password: OTMANE123@otmane

test:
  <<: *default
  database: chefchapters_test
  username: postgres
  password: OTMANE123@otmane

production:
  <<: *default
  database: chefchapters_production
  username: chefchapters
  password: OTMANE123@otmane
  